/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author hoirs
 */
public class MenuUtama_2011500432_SyahbaniHoir extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama_2011500432_SyahbaniHoir() {
        initComponents();
        this.setSize(1000,600);
        setLocationRelativeTo(this);
        Koneksi.Database_2011500432_SyahbaniHoir.KoneksiDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MMenu = new javax.swing.JMenu();
        MBuku = new javax.swing.JMenuItem();
        MtTransaksi = new javax.swing.JMenu();
        TPeminjaman = new javax.swing.JMenuItem();
        MLaporan = new javax.swing.JMenu();
        LaporanBuku = new javax.swing.JMenuItem();
        Mexit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        MMenu.setText("File Master");
        MMenu.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMenuActionPerformed(evt);
            }
        });

        MBuku.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MBuku.setText("Entri Data Buku");
        MBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBukuActionPerformed(evt);
            }
        });
        MMenu.add(MBuku);

        jMenuBar1.add(MMenu);

        MtTransaksi.setText("Transaksi");
        MtTransaksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        TPeminjaman.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TPeminjaman.setText("Peminjaman");
        TPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TPeminjamanActionPerformed(evt);
            }
        });
        MtTransaksi.add(TPeminjaman);

        jMenuBar1.add(MtTransaksi);

        MLaporan.setText("Laporan");
        MLaporan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        LaporanBuku.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LaporanBuku.setText("Laporan Daftar Buku");
        LaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanBukuActionPerformed(evt);
            }
        });
        MLaporan.add(LaporanBuku);

        jMenuBar1.add(MLaporan);

        Mexit.setText("Exit");
        Mexit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Mexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MexitMouseClicked(evt);
            }
        });
        jMenuBar1.add(Mexit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(882, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MexitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MexitMouseClicked

    private void TPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TPeminjamanActionPerformed
        View.TPeminjamanBuku_2011500432_SyahbaniHoir T = new View.TPeminjamanBuku_2011500432_SyahbaniHoir();
        T.setVisible(true);
        setLocationRelativeTo(this);
//        T.getTxtkdplg.requestFocus();
    }//GEN-LAST:event_TPeminjamanActionPerformed

    private void MMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMenuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MMenuActionPerformed

    private void MBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBukuActionPerformed
//         TODO add your handling code here:
                View.MBuku_2011500432_SyahbaniHoir p = new View.MBuku_2011500432_SyahbaniHoir();
                p.setVisible(true);
                setLocationRelativeTo(this);

    }//GEN-LAST:event_MBukuActionPerformed

    private void LaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanBukuActionPerformed
        View.LapBuku_2011500432_SyahbaniHoir B = new View.LapBuku_2011500432_SyahbaniHoir();
        B.setVisible(true);
        setLocationRelativeTo(this);
    }//GEN-LAST:event_LaporanBukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_2011500432_SyahbaniHoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_2011500432_SyahbaniHoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_2011500432_SyahbaniHoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama_2011500432_SyahbaniHoir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama_2011500432_SyahbaniHoir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem LaporanBuku;
    private javax.swing.JMenuItem MBuku;
    private javax.swing.JMenu MLaporan;
    private javax.swing.JMenu MMenu;
    private javax.swing.JMenu Mexit;
    private javax.swing.JMenu MtTransaksi;
    private javax.swing.JMenuItem TPeminjaman;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables

    
}
